# Generated by Django 4.1.3 on 2023-01-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(max_length=255)),
                ("desc1", models.CharField(max_length=255)),
                ("birthday", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("website", models.CharField(max_length=30)),
                ("phone", models.IntegerField()),
                ("city", models.CharField(max_length=30)),
                ("degree", models.CharField(max_length=30)),
                ("phemailone", models.EmailField(max_length=254)),
                ("freelance", models.CharField(max_length=25)),
                ("desc2", models.CharField(max_length=255)),
                ("happyclients", models.IntegerField()),
                ("projects", models.IntegerField()),
                ("hours_of_support", models.IntegerField()),
                ("awards", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adress", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(max_length=150)),
                ("desc", models.CharField(max_length=150)),
                ("link1", models.CharField(max_length=150, verbose_name="linkedin")),
                ("link2", models.CharField(max_length=150, verbose_name="facebook")),
                ("link3", models.CharField(max_length=150, verbose_name="instagram")),
                ("link4", models.CharField(max_length=150, verbose_name="telegram")),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Resume_five",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=20)),
                ("small_desc", models.CharField(max_length=35)),
                ("desc", models.CharField(max_length=200)),
                ("text_one", models.CharField(max_length=255)),
                ("text_two", models.CharField(max_length=255)),
                ("text_three", models.CharField(max_length=255)),
                ("text_four", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Resume_four",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("small_desc", models.CharField(max_length=35)),
                ("year", models.CharField(max_length=20)),
                ("text_one", models.CharField(max_length=255)),
                ("text_two", models.CharField(max_length=255)),
                ("text_three", models.CharField(max_length=255)),
                ("text_four", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Resume_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("small_desc", models.CharField(max_length=35)),
                ("desc", models.CharField(max_length=200)),
                ("bio", models.CharField(max_length=20)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Resume_three",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=20)),
                ("small_desc", models.CharField(max_length=35)),
                ("desc", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Resume_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("small_desc", models.CharField(max_length=35)),
                ("year", models.CharField(max_length=20)),
                ("desc", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(max_length=50)),
                ("desc1", models.CharField(max_length=200)),
                ("name2", models.CharField(max_length=50)),
                ("desc2", models.CharField(max_length=200)),
                ("name3", models.CharField(max_length=50)),
                ("desc3", models.CharField(max_length=200)),
                ("name4", models.CharField(max_length=50)),
                ("desc4", models.CharField(max_length=200)),
                ("name5", models.CharField(max_length=50)),
                ("desc5", models.CharField(max_length=200)),
                ("name6", models.CharField(max_length=50)),
                ("desc6", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
