# Generated by Django 4.1.3 on 2023-01-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_about_contact_home_portfolio_resume_five_resume_four_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="name1",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="name2",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="name3",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="name4",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
