# Generated by Django 4.1.3 on 2023-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_resume_two_small_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume_four",
            name="desc",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
