# Generated by Django 4.1.3 on 2023-01-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_img_portfolio_img_five_portfolio_img_four_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="link5",
            field=models.CharField(default=1, max_length=255, verbose_name="twitter"),
            preserve_default=False,
        ),
    ]
