# Generated by Django 4.1.3 on 2023-01-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_home_link5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="link1",
            field=models.EmailField(max_length=254, verbose_name="linkedin"),
        ),
        migrations.AlterField(
            model_name="home",
            name="link2",
            field=models.EmailField(max_length=254, verbose_name="facebook"),
        ),
        migrations.AlterField(
            model_name="home",
            name="link3",
            field=models.EmailField(max_length=254, verbose_name="instagram"),
        ),
        migrations.AlterField(
            model_name="home",
            name="link4",
            field=models.EmailField(max_length=254, verbose_name="telegram"),
        ),
        migrations.AlterField(
            model_name="home",
            name="link5",
            field=models.EmailField(max_length=254, verbose_name="twitter"),
        ),
    ]
